AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the outfit products
Resources:
  SAMFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.api_handler.lambda_handler
      Runtime: python3.7
      CodeUri: ./OutfitBundler/
      Environment:
        Variables:
          APP_ENVIRONMENT: 'qa'
